### ISSUE TITLE
20 мая 2017. Задача 1. Почему в условиях X это матрица n x n, а не n x m?

### ISSUE THREAD

**Issue by philip-bl** [efiminem/supershad#3]
Сабж. Обозначение Mat_n (R) это матрицы R^{n x n}, ведь правда? То, что я решил задачу для любого m, а не только для m=n, наталкивает меня на мысли, что я что-то не так понял.

**Comment by efiminem** [comment]
Правда, Mat_n (R) обозначает кольцо n x n матриц над полем R. Для любого m решить задачу невозможно, потому что понятия симметричности и положительной определенности распространяются только на квадратные матрицы.

**Comment by philip-bl** [comment]
Я про второе упоминание Mat в тексте. Первое - понятно. А почему во втором требуют квадратную матрицу, непонятно. Ведь если размер A nxn, размер X nxm, то все хорошо умножается.

**Comment by efiminem** [comment]
Тогда согласен, во втором упоминании такое условие не обязательно. Предполагаю, что его добавили просто чтобы не усложнять. Потому что никаких новых идей рассмотрение более широкого множества не требует.
