### ISSUE TITLE
Ошибка в 7 задаче 3 июня 2012

### ISSUE THREAD

**Issue by mkspopov** [efiminem/supershad#7]
Критерий Сильвестра не работает для неотрицательно определенных матриц. Есть контрпример на википедии. Также с википедии:
"Для положительно полуопределённых матриц критерий звучит подобным образом: Форма положительно полуопределена тогда и только тогда, когда все главные миноры неотрицательны. Здесь главным минором называется определитель подматрицы симметричной относительно главной диагонали, то есть подматрицы, у которой множества задающих её номеров столбцов и строк одинаковые (напр. 1-й и 3-й столбцы и строки, на пересечении которых расположена матрица)."

**Comment by koddo** [comment]
Может, использовать следующий факт?

> Матрица будет положительно полуопределённой тогда и только тогда, когда она является матрицей Грама какого-нибудь множества векторов. В отличие от положительно определённой матрицы данные векторы не обязательно линейно независимы. 

<https://ru.wikipedia.org/wiki/Положительно_определённая_матрица#Отрицательно_определённая,_полуопределённая_и_неопределённая_матрицы>

**Comment by efiminem** [comment]
Замечание справедливое. Впрочем, решение это почти не меняет. Исправил и написал подробнее про определители.
