### ISSUE TITLE
Ошибка в решении задачи №1 варианта от 9 июня 2013 года

### ISSUE THREAD

**Issue by dqdp** [efiminem/supershad#9]
Ошибка в одном  знаке. Правильный ответ - 
<img src="https://render.githubusercontent.com/render/math?math=\Large a_n=\frac{1}{1%2B\sum_{1}^{n}{k}}=\frac{1}{1%2B\frac{n(n%2B1)}{2}}=\frac{2}{n(n%2B1)%2B2}">
в чем можно убедиться непосредственно.

**Comment by efiminem** [comment]
Почему? a_1 должен быть равен 1, а не 1/2.

**Comment by dqdp** [comment]
Да, меня что-то переклинило, сорри)
